[package]
name = "neodonut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "donut"
path = "src/donut.rs"

[[bin]]
name = "neodonut"
path = "src/neodonut.rs"

[dependencies]
terminal_size = "0.2"
rand = "0.8.0"
